name: 'Github Pages Deployment'

on:
  push:
    branches:
      - master
      - data

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout makefile
        uses: actions/checkout@v2
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          ref: 'data'
          path: 'data'
      - name: Use docker to generate html files
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          make

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.coder17.com
